scriptencoding utf-8
if has('vim_starting') && has('reltime') && !has('win32') "{{{
  augroup VimStart
    autocmd!
    let g:startuptime = reltime()
    autocmd VimEnter * let g:startuptime = reltime(g:startuptime) | echomsg 'startuptime: ' . reltimestr(g:startuptime)
  augroup END
endif "}}}
if !has('nvim') "{{{
  if v:version >= 800 || has('patch-7.4.2111') "{{{
    unlet! skip_defaults_vim
    source $VIMRUNTIME/defaults.vim
  endif "}}}
  if &term=~"^xterm\\|rxvt" "{{{
    let &t_Co = 256
    let &t_te.="\e[0 q"
    let &t_ti.="\e[2 q"
    let &t_EI.="\e[2 q"
    let &t_SI.="\e[6 q"
    let &t_SR.="\e[4 q"
    let &t_vb ="[?5h$<100>[?5l"
  endif "}}}
  if executable('sl') && !has('gui_running') "{{{
    function! g:SL(...)
      if has('sound')
        "https://upload.wikimedia.org/wikipedia/commons/9/96/D51498.kiteki.2014.ogg
        let s:whistle=expand('~/.vim/D51498.kiteki.2014.ogg')
        "https://voyager.jpl.nasa.gov/assets/audio/golden-record/train.wav
        "let s:whistle=expand('~/.vim/train.wav')
        "http://www.oslivesteam.com/sounds/whistle2.wav
        "let s:whistle=expand('~/.vim/whistle2.wav')
        if filereadable(s:whistle)
          echo sound_playfile(s:whistle)
        endif
      endif
      silent !sl
      redraw!
    endfunction
    if !exists(":SL")
      command! -nargs=? SL call SL(<f-args>)
      cnoreabbrev sl SL
    endif
  endif "}}}
  if has('win32') "{{{
    set runtimepath^=$HOME/.vim
    set runtimepath+=$HOME/.vim/after
    let &packpath = &runtimepath
    set t_ut=
  endif "}}}
  source ~/.exrc
  set helplang=ja,en,ru
else
  silent! source ~/.exrc
endif "}}}
if executable('evince') "{{{
  command! Evince !evince %:r.pdf &
endif "}}}
if executable('factor') "{{{
  command! -nargs=1 Pf let @+=substitute(substitute(system('factor',<q-args>),": ","=","")," ","*","g") | echomsg expand(@+)
endif "}}}
augroup ScratchBuffer "{{{
  autocmd!
  autocmd StdinReadPre * setlocal buftype=nofile bufhidden=hide noswapfile
augroup END "}}}
if has('syntax') "{{{
  syntax enable
  augroup HighlightTuning
    autocmd!
    autocmd ColorScheme * highlight Normal ctermbg=NONE guibg=NONE
    autocmd ColorScheme * highlight ColorColumn ctermbg=DarkGrey
    autocmd ColorScheme * highlight Conceal ctermbg=NONE guibg=NONE
    autocmd ColorScheme * highlight CursorLine ctermbg=NONE cterm=NONE guibg=NONE
    autocmd ColorScheme * highlight CursorLineNr ctermfg=Yellow guifg=Yellow
    autocmd ColorScheme * highlight EndOfBuffer ctermbg=NONE guibg=NONE
    autocmd ColorScheme * highlight Folded ctermbg=NONE guibg=NONE
    autocmd ColorScheme * highlight Identifier ctermfg=LightMagenta guifg=LightMagenta
    autocmd ColorScheme * highlight LineNr ctermfg=DarkCyan guifg=DarkCyan
    autocmd ColorScheme * highlight Special ctermfg=LightRed guifg=LightRed
  augroup END
  colorscheme industry
  filetype plugin indent on
  let &colorcolumn='+'.join(range(1,256),',+')
endif "}}}
if has('eval') "{{{
  let g:changelog_dateformat="%Y-%m-%d" " ~/.vim/ftplugin/changelog.vim
  let g:eskk#egg_like_newline=1
  let g:eskk#use_azik=1
  let g:eskk#azik_keyboard_type="us101"
  let g:html_indent_script1 = "auto"    " ~/.vim/ftplugin/html.vim
  let g:html_indent_style1 = "auto"
  let g:loaded_matchparen=1
  if has('patch-7.3.32')
    let g:plugin_skk_disable=1
  endif
  let g:python_recommended_style=0      " ~/.vim/ftplugin/python.vim
  let g:rst_style=1
  let g:tex_conceal="bdmg"
  let g:tex_flavor="latex"              " ~/.vim/ftplugin/tex.vim
  let g:tex_fold_enabled=1
  let g:vimsyn_folding="af"
  augroup EskkInit "{{{
    autocmd!
    autocmd User eskk-initialize-pre call s:eskk_initial_pre()
    autocmd User eskk-initialize-post call s:eskk_initial_post()
    if !g:eskk#use_azik
      autocmd User eskk-enable-post lnoremap <buffer> l <Plug>(eskk:disable)
    endif
  augroup END "}}}
  function! s:eskk_initial_pre() abort "{{{
    if g:eskk#use_azik "{{{
      let t = eskk#table#new('rom_to_hira*', 'rom_to_hira') "{{{
      call t.add_map('x[', '「')
      call t.add_map('_', '「')
      call t.add_map('z_', '『')
      call t.add_map('z(', '（')
      call t.add_map('z)', '）')
      call t.add_map('z{', '【')
      call t.add_map('z}', '】')
      call t.add_map('z ', '　')
      call t.add_map('z*', '※')
      call t.add_map('z0', '○')
      call t.add_map('z@', '◎')
      call t.add_map('xxh', '←')
      call t.add_map('xxj', '↓')
      call t.add_map('xxk', '↑')
      call t.add_map('xxl', '→')
      call t.add_map('''', 'ー')
      call t.add_map(':', 'ー')
      call t.add_map('z:', '゜')
      call t.add_map('z;', '゛')
      call t.add_map('a', 'あ')
      call t.add_map('i', 'い')
      call t.add_map('u', 'う')
      call t.add_map('e', 'え')
      call t.add_map('o', 'お')
      call t.add_map('ka', 'か')
      call t.add_map('ki', 'き')
      call t.add_map('kf', 'き')
      call t.add_map('ku', 'く')
      call t.add_map('ke', 'け')
      call t.add_map('ko', 'こ')
      call t.add_map('sa', 'さ')
      call t.add_map('si', 'し')
      call t.add_map('su', 'す')
      call t.add_map('se', 'せ')
      call t.add_map('so', 'そ')
      call t.add_map('ta', 'た')
      call t.add_map('ti', 'ち')
      call t.add_map('tsu', 'つ')
      call t.add_map('tu', 'つ')
      call t.add_map('te', 'て')
      call t.add_map('to', 'と')
      call t.add_map('na', 'な')
      call t.add_map('ni', 'に')
      call t.add_map('nu', 'ぬ')
      call t.add_map('nf', 'ぬ')
      call t.add_map('ne', 'ね')
      call t.add_map('no', 'の')
      call t.add_map('ha', 'は')
      call t.add_map('hi', 'ひ')
      call t.add_map('hu', 'ふ')
      call t.add_map('hf', 'ふ')
      call t.add_map('he', 'へ')
      call t.add_map('ho', 'ほ')
      call t.add_map('fa', 'ふぁ')
      call t.add_map('fi', 'ふぃ')
      call t.add_map('fu', 'ふ')
      call t.add_map('fe', 'ふぇ')
      call t.add_map('fo', 'ふぉ')
      call t.add_map('ma', 'ま')
      call t.add_map('mi', 'み')
      call t.add_map('mu', 'む')
      call t.add_map('mf', 'む')
      call t.add_map('me', 'め')
      call t.add_map('mo', 'も')
      call t.add_map('ya', 'や')
      call t.add_map('yi', 'い')
      call t.add_map('yu', 'ゆ')
      call t.add_map('yf', 'ゆ')
      call t.add_map('ye', 'いぇ')
      call t.add_map('yo', 'よ')
      call t.add_map('ra', 'ら')
      call t.add_map('ri', 'り')
      call t.add_map('ru', 'る')
      call t.add_map('re', 'れ')
      call t.add_map('ro', 'ろ')
      call t.add_map('wa', 'わ')
      call t.add_map('wi', 'ゐ')
      call t.add_map('wu', 'う')
      call t.add_map('we', 'ゑ')
      call t.add_map('wo', 'を')
      call t.add_map('q', 'ん')
      call t.add_map('kz', 'かん')
      call t.add_map('kn', 'かん')
      call t.add_map('kk', 'きん')
      call t.add_map('kj', 'くん')
      call t.add_map('kd', 'けん')
      call t.add_map('kl', 'こん')
      call t.add_map('sz', 'さん')
      call t.add_map('sn', 'さん')
      call t.add_map('sk', 'しん')
      call t.add_map('sj', 'すん')
      call t.add_map('sd', 'せん')
      call t.add_map('sl', 'そん')
      call t.add_map('tz', 'たん')
      call t.add_map('tn', 'たん')
      call t.add_map('tk', 'ちん')
      call t.add_map('tj', 'つん')
      call t.add_map('td', 'てん')
      call t.add_map('tl', 'とん')
      call t.add_map('nz', 'なん')
      call t.add_map('nn', 'ん')
      call t.add_map('nk', 'にん')
      call t.add_map('nj', 'ぬん')
      call t.add_map('nd', 'ねん')
      call t.add_map('nl', 'のん')
      call t.add_map('hz', 'はん')
      call t.add_map('hn', 'はん')
      call t.add_map('hk', 'ひん')
      call t.add_map('hj', 'ふん')
      call t.add_map('hd', 'へん')
      call t.add_map('hl', 'ほん')
      call t.add_map('fz', 'ふぁん')
      call t.add_map('fn', 'ふぁん')
      call t.add_map('fk', 'ふぃん')
      call t.add_map('fj', 'ふん')
      call t.add_map('fd', 'ふぇん')
      call t.add_map('fl', 'ふぉん')
      call t.add_map('mz', 'まん')
      call t.add_map('mk', 'みん')
      call t.add_map('mj', 'むん')
      call t.add_map('md', 'めん')
      call t.add_map('ml', 'もん')
      call t.add_map('yz', 'やん')
      call t.add_map('yn', 'やん')
      call t.add_map('yj', 'ゆん')
      call t.add_map('yl', 'よん')
      call t.add_map('rz', 'らん')
      call t.add_map('rn', 'らん')
      call t.add_map('rk', 'りん')
      call t.add_map('rj', 'るん')
      call t.add_map('rd', 'れん')
      call t.add_map('rl', 'ろん')
      call t.add_map('wz', 'わん')
      call t.add_map('wn', 'わん')
      call t.add_map('wk', 'うぃん')
      call t.add_map('wd', 'うぇん')
      call t.add_map('wl', 'うぉん')
      call t.add_map('kq', 'かい')
      call t.add_map('kh', 'くう')
      call t.add_map('kw', 'けい')
      call t.add_map('kp', 'こう')
      call t.add_map('sq', 'さい')
      call t.add_map('sh', 'すう')
      call t.add_map('sw', 'せい')
      call t.add_map('sp', 'そう')
      call t.add_map('tq', 'たい')
      call t.add_map('th', 'つう')
      call t.add_map('tw', 'てい')
      call t.add_map('tp', 'とう')
      call t.add_map('nq', 'ない')
      call t.add_map('nh', 'ぬう')
      call t.add_map('nw', 'ねい')
      call t.add_map('np', 'のう')
      call t.add_map('hq', 'はい')
      call t.add_map('hh', 'ふう')
      call t.add_map('hw', 'へい')
      call t.add_map('hp', 'ほう')
      call t.add_map('fq', 'ふぁい')
      call t.add_map('fh', 'ふう')
      call t.add_map('fw', 'ふぇい')
      call t.add_map('fp', 'ふぉー')
      call t.add_map('mq', 'まい')
      call t.add_map('mh', 'むう')
      call t.add_map('mw', 'めい')
      call t.add_map('mp', 'もう')
      call t.add_map('yq', 'やい')
      call t.add_map('yh', 'ゆう')
      call t.add_map('yp', 'よう')
      call t.add_map('rq', 'らい')
      call t.add_map('rh', 'るう')
      call t.add_map('rw', 'れい')
      call t.add_map('rp', 'ろう')
      call t.add_map('wq', 'わい')
      call t.add_map('wp', 'うぉー')
      call t.add_map('ga', 'が')
      call t.add_map('gi', 'ぎ')
      call t.add_map('gu', 'ぐ')
      call t.add_map('ge', 'げ')
      call t.add_map('go', 'ご')
      call t.add_map('za', 'ざ')
      call t.add_map('zi', 'じ')
      call t.add_map('zu', 'ず')
      call t.add_map('ze', 'ぜ')
      call t.add_map('zo', 'ぞ')
      call t.add_map('da', 'だ')
      call t.add_map('di', 'ぢ')
      call t.add_map('du', 'づ')
      call t.add_map('de', 'で')
      call t.add_map('df', 'で')
      call t.add_map('do', 'ど')
      call t.add_map('ba', 'ば')
      call t.add_map('bi', 'び')
      call t.add_map('bu', 'ぶ')
      call t.add_map('be', 'べ')
      call t.add_map('bo', 'ぼ')
      call t.add_map('pa', 'ぱ')
      call t.add_map('pi', 'ぴ')
      call t.add_map('pu', 'ぷ')
      call t.add_map('pe', 'ぺ')
      call t.add_map('po', 'ぽ')
      call t.add_map('gz', 'がん')
      call t.add_map('gn', 'がん')
      call t.add_map('gk', 'ぎん')
      call t.add_map('gj', 'ぐん')
      call t.add_map('gd', 'げん')
      call t.add_map('gl', 'ごん')
      call t.add_map('zz', 'ざん')
      call t.add_map('zn', 'ざん')
      call t.add_map('zk', 'じん')
      call t.add_map('zj', 'ずん')
      call t.add_map('zd', 'ぜん')
      call t.add_map('zl', 'ぞん')
      call t.add_map('dz', 'だん')
      call t.add_map('dn', 'だん')
      call t.add_map('dk', 'ぢん')
      call t.add_map('dj', 'づん')
      call t.add_map('dd', 'でん')
      call t.add_map('dl', 'どん')
      call t.add_map('bz', 'ばん')
      call t.add_map('bn', 'ばん')
      call t.add_map('bk', 'びん')
      call t.add_map('bj', 'ぶん')
      call t.add_map('bd', 'べん')
      call t.add_map('bl', 'ぼん')
      call t.add_map('pz', 'ぱん')
      call t.add_map('pn', 'ぱん')
      call t.add_map('pk', 'ぴん')
      call t.add_map('pj', 'ぷん')
      call t.add_map('pd', 'ぺん')
      call t.add_map('pl', 'ぽん')
      call t.add_map('gq', 'がい')
      call t.add_map('gh', 'ぐう')
      call t.add_map('gw', 'げい')
      call t.add_map('gp', 'ごう')
      call t.add_map('zq', 'ざい')
      call t.add_map('zh', 'ずう')
      call t.add_map('zw', 'ぜい')
      call t.add_map('zp', 'ぞう')
      call t.add_map('dq', 'だい')
      call t.add_map('dh', 'づう')
      call t.add_map('dw', 'でい')
      call t.add_map('dp', 'どう')
      call t.add_map('bq', 'ばい')
      call t.add_map('bh', 'ぶう')
      call t.add_map('bw', 'べい')
      call t.add_map('bp', 'ぼう')
      call t.add_map('pq', 'ぱい')
      call t.add_map('ph', 'ぷう')
      call t.add_map('pw', 'ぺい')
      call t.add_map('pp', 'ぽう')
      call t.add_map('zc', 'ざ')
      call t.add_map('zv', 'ざい')
      call t.add_map('zx', 'ぜい')
      call t.add_map('kya', 'きゃ')
      call t.add_map('kyi', 'きぃ')
      call t.add_map('kyu', 'きゅ')
      call t.add_map('kye', 'きぇ')
      call t.add_map('kyo', 'きょ')
      call t.add_map('kga', 'きゃ')
      call t.add_map('kgi', 'い')
      call t.add_map('kgu', 'きゅ')
      call t.add_map('kge', 'きぇ')
      call t.add_map('kgo', 'きょ')
      call t.add_map('sya', 'しゃ')
      call t.add_map('syi', 'しぃ')
      call t.add_map('syu', 'しゅ')
      call t.add_map('sye', 'しぇ')
      call t.add_map('syo', 'しょ')
      call t.add_map('xa', 'しゃ')
      call t.add_map('xi', 'し')
      call t.add_map('xu', 'しゅ')
      call t.add_map('xe', 'しぇ')
      call t.add_map('xo', 'しょ')
      call t.add_map('tya', 'ちゃ')
      call t.add_map('tyi', 'ちぃ')
      call t.add_map('tyu', 'ちゅ')
      call t.add_map('tye', 'ちぇ')
      call t.add_map('tyo', 'ちょ')
      call t.add_map('ca', 'ちゃ')
      call t.add_map('ci', 'ち')
      call t.add_map('cu', 'ちゅ')
      call t.add_map('ce', 'ちぇ')
      call t.add_map('co', 'ちょ')
      call t.add_map('nya', 'にゃ')
      call t.add_map('nyi', 'にぃ')
      call t.add_map('nyu', 'にゅ')
      call t.add_map('nye', 'にぇ')
      call t.add_map('nyo', 'にょ')
      call t.add_map('nga', 'にゃ')
      call t.add_map('ngi', 'い')
      call t.add_map('ngu', 'にゅ')
      call t.add_map('nge', 'にぇ')
      call t.add_map('ngo', 'にょ')
      call t.add_map('hya', 'ひゃ')
      call t.add_map('hyi', 'ひぃ')
      call t.add_map('hyu', 'ひゅ')
      call t.add_map('hye', 'ひぇ')
      call t.add_map('hyo', 'ひょ')
      call t.add_map('hga', 'ひゃ')
      call t.add_map('hgi', 'い')
      call t.add_map('hgu', 'ひゅ')
      call t.add_map('hge', 'ひぇ')
      call t.add_map('hgo', 'ひょ')
      call t.add_map('mya', 'みゃ')
      call t.add_map('myi', 'みぃ')
      call t.add_map('myu', 'みゅ')
      call t.add_map('mye', 'みぇ')
      call t.add_map('myo', 'みょ')
      call t.add_map('mga', 'みゃ')
      call t.add_map('mgi', 'い')
      call t.add_map('mgu', 'みゅ')
      call t.add_map('mge', 'みぇ')
      call t.add_map('mgo', 'みょ')
      call t.add_map('rya', 'りゃ')
      call t.add_map('ryi', 'りぃ')
      call t.add_map('ryu', 'りゅ')
      call t.add_map('rye', 'りぇ')
      call t.add_map('ryo', 'りょ')
      call t.add_map('kyz', 'きゃん')
      call t.add_map('kyn', 'きゃん')
      call t.add_map('kyj', 'きゅん')
      call t.add_map('kyd', 'きぇん')
      call t.add_map('kyl', 'きょん')
      call t.add_map('kgz', 'きゃん')
      call t.add_map('kgn', 'きゃん')
      call t.add_map('kgj', 'きゅん')
      call t.add_map('kgd', 'きぇん')
      call t.add_map('kgl', 'きょん')
      call t.add_map('syz', 'しゃん')
      call t.add_map('syn', 'しゃん')
      call t.add_map('syj', 'しゅん')
      call t.add_map('syd', 'しぇん')
      call t.add_map('syl', 'しょん')
      call t.add_map('xz', 'しゃん')
      call t.add_map('xn', 'しゃん')
      call t.add_map('xj', 'しゅん')
      call t.add_map('xd', 'しぇん')
      call t.add_map('xl', 'しょん')
      call t.add_map('tyz', 'ちゃん')
      call t.add_map('tyn', 'ちゃん')
      call t.add_map('tyj', 'ちゅん')
      call t.add_map('tyd', 'ちぇん')
      call t.add_map('tyl', 'ちょん')
      call t.add_map('cz', 'ちゃん')
      call t.add_map('cn', 'ちゃん')
      call t.add_map('cj', 'ちゅん')
      call t.add_map('cd', 'ちぇん')
      call t.add_map('cl', 'ちょん')
      call t.add_map('nyz', 'にゃん')
      call t.add_map('nyn', 'にゃん')
      call t.add_map('nyj', 'にゅん')
      call t.add_map('nyd', 'にぇん')
      call t.add_map('nyl', 'にょん')
      call t.add_map('ngz', 'にゃん')
      call t.add_map('ngn', 'にゃん')
      call t.add_map('ngj', 'にゅん')
      call t.add_map('ngd', 'にぇん')
      call t.add_map('ngl', 'にょん')
      call t.add_map('hyz', 'ひゃん')
      call t.add_map('hyn', 'ひゃん')
      call t.add_map('hyj', 'ひゅん')
      call t.add_map('hyd', 'ひぇん')
      call t.add_map('hyl', 'ひょん')
      call t.add_map('hgz', 'ひゃん')
      call t.add_map('hgn', 'ひゃん')
      call t.add_map('hgj', 'ひゅん')
      call t.add_map('hgd', 'ひぇん')
      call t.add_map('hgl', 'ひょん')
      call t.add_map('myz', 'みゃん')
      call t.add_map('myn', 'みゃん')
      call t.add_map('myj', 'みゅん')
      call t.add_map('myd', 'みぇん')
      call t.add_map('myl', 'みょん')
      call t.add_map('mgz', 'みゃん')
      call t.add_map('mgn', 'みゃん')
      call t.add_map('mgj', 'みゅん')
      call t.add_map('mgd', 'みぇん')
      call t.add_map('mgl', 'みょん')
      call t.add_map('ryz', 'りゃん')
      call t.add_map('ryn', 'りゃん')
      call t.add_map('ryj', 'りゅん')
      call t.add_map('ryd', 'りぇん')
      call t.add_map('ryl', 'りょん')
      call t.add_map('kyq', 'きゃい')
      call t.add_map('kyh', 'きゅう')
      call t.add_map('kyw', 'きぇい')
      call t.add_map('kyp', 'きょう')
      call t.add_map('kgq', 'きゃい')
      call t.add_map('kgh', 'きゅう')
      call t.add_map('kgw', 'きぇい')
      call t.add_map('kgp', 'きょう')
      call t.add_map('syq', 'しゃい')
      call t.add_map('syh', 'しゅう')
      call t.add_map('syw', 'しぇい')
      call t.add_map('syp', 'しょう')
      call t.add_map('xq', 'しゃい')
      call t.add_map('xh', 'しゅう')
      call t.add_map('xw', 'しぇい')
      call t.add_map('xp', 'しょう')
      call t.add_map('tyq', 'ちゃい')
      call t.add_map('tyh', 'ちゅう')
      call t.add_map('tyw', 'ちぇい')
      call t.add_map('typ', 'ちょう')
      call t.add_map('cq', 'ちゃい')
      call t.add_map('ch', 'ちゅう')
      call t.add_map('cw', 'ちぇい')
      call t.add_map('cp', 'ちょう')
      call t.add_map('nyq', 'にゃい')
      call t.add_map('nyh', 'にゅう')
      call t.add_map('nyw', 'にぇい')
      call t.add_map('nyp', 'にょう')
      call t.add_map('ngq', 'にゃい')
      call t.add_map('ngh', 'にゅう')
      call t.add_map('ngw', 'にぇい')
      call t.add_map('ngp', 'にょう')
      call t.add_map('hyq', 'ひゃい')
      call t.add_map('hyh', 'ひゅう')
      call t.add_map('hyw', 'ひぇい')
      call t.add_map('hyp', 'ひょう')
      call t.add_map('hgq', 'ひゃい')
      call t.add_map('hgh', 'ひゅう')
      call t.add_map('hgw', 'ひぇい')
      call t.add_map('hgp', 'ひょう')
      call t.add_map('myq', 'みゃい')
      call t.add_map('myh', 'みゅう')
      call t.add_map('myw', 'みぇい')
      call t.add_map('myp', 'みょう')
      call t.add_map('mgq', 'みゃい')
      call t.add_map('mgh', 'みゅう')
      call t.add_map('mgw', 'みぇい')
      call t.add_map('mgp', 'みょう')
      call t.add_map('ryq', 'りゃい')
      call t.add_map('ryh', 'りゅう')
      call t.add_map('ryw', 'りぇい')
      call t.add_map('ryp', 'りょう')
      call t.add_map('gya', 'ぎゃ')
      call t.add_map('gyu', 'ぎゅ')
      call t.add_map('gye', 'ぎぇ')
      call t.add_map('gyo', 'ぎょ')
      call t.add_map('zya', 'じゃ')
      call t.add_map('zyu', 'じゅ')
      call t.add_map('zye', 'じぇ')
      call t.add_map('zyo', 'じょ')
      call t.add_map('jya', 'じゃ')
      call t.add_map('jyu', 'じゅ')
      call t.add_map('jye', 'じぇ')
      call t.add_map('jyo', 'じょ')
      call t.add_map('ja', 'じゃ')
      call t.add_map('ji', 'じ')
      call t.add_map('ju', 'じゅ')
      call t.add_map('je', 'じぇ')
      call t.add_map('jo', 'じょ')
      call t.add_map('bya', 'びゃ')
      call t.add_map('byu', 'びゅ')
      call t.add_map('bye', 'びぇ')
      call t.add_map('byo', 'びょ')
      call t.add_map('pya', 'ぴゃ')
      call t.add_map('pyu', 'ぴゅ')
      call t.add_map('pye', 'ぴぇ')
      call t.add_map('pyo', 'ぴょ')
      call t.add_map('pga', 'ぴゃ')
      call t.add_map('pgi', 'い')
      call t.add_map('pgu', 'ぴゅ')
      call t.add_map('pge', 'ぴぇ')
      call t.add_map('pgo', 'ぴょ')
      call t.add_map('gyz', 'ぎゃん')
      call t.add_map('gyn', 'ぎゃん')
      call t.add_map('gyj', 'ぎゅん')
      call t.add_map('gyd', 'ぎぇん')
      call t.add_map('gyl', 'ぎょん')
      call t.add_map('zyz', 'じゃん')
      call t.add_map('zyn', 'じゃん')
      call t.add_map('zyj', 'じゅん')
      call t.add_map('zyd', 'じぇん')
      call t.add_map('zyl', 'じょん')
      call t.add_map('jz', 'じゃん')
      call t.add_map('jn', 'じゃん')
      call t.add_map('jk', 'じん')
      call t.add_map('jj', 'じゅん')
      call t.add_map('jd', 'じぇん')
      call t.add_map('jl', 'じょん')
      call t.add_map('byz', 'びゃん')
      call t.add_map('byn', 'びゃん')
      call t.add_map('byj', 'びゅん')
      call t.add_map('byd', 'びぇん')
      call t.add_map('byl', 'びょん')
      call t.add_map('pyz', 'ぴゃん')
      call t.add_map('pyn', 'ぴゃん')
      call t.add_map('pyj', 'ぴゅん')
      call t.add_map('pyd', 'ぴぇん')
      call t.add_map('pyl', 'ぴょん')
      call t.add_map('pgz', 'ぴゃん')
      call t.add_map('pgn', 'ぴゃん')
      call t.add_map('pgj', 'ぴゅん')
      call t.add_map('pgd', 'ぴぇん')
      call t.add_map('pgl', 'ぴょん')
      call t.add_map('gyq', 'ぎゃい')
      call t.add_map('gyh', 'ぎゅう')
      call t.add_map('gyw', 'ぎぇい')
      call t.add_map('gyp', 'ぎょう')
      call t.add_map('zyq', 'じゃい')
      call t.add_map('zyh', 'じゅう')
      call t.add_map('zyw', 'じぇい')
      call t.add_map('zyp', 'じょう')
      call t.add_map('jq', 'じゃい')
      call t.add_map('jh', 'じゅう')
      call t.add_map('jw', 'じぇい')
      call t.add_map('jp', 'じょう')
      call t.add_map('byq', 'びゃい')
      call t.add_map('byh', 'びゅう')
      call t.add_map('byw', 'びぇい')
      call t.add_map('byp', 'びょう')
      call t.add_map('pyq', 'ぴゃい')
      call t.add_map('pyh', 'ぴゅう')
      call t.add_map('pyw', 'ぴぇい')
      call t.add_map('pyp', 'ぴょう')
      call t.add_map('pgq', 'ぴゃい')
      call t.add_map('pgh', 'ぴゅう')
      call t.add_map('pgw', 'ぴぇい')
      call t.add_map('pgp', 'ぴょう')
      call t.add_map('va', 'う゛ぁ')
      call t.add_map('vi', 'う゛ぃ')
      call t.add_map('vu', 'う゛')
      call t.add_map('ve', 'う゛ぇ')
      call t.add_map('vo', 'う゛ぉ')
      call t.add_map('tgi', 'てぃ')
      call t.add_map('tgu', 'とぅ')
      call t.add_map('dci', 'でぃ')
      call t.add_map('dcu', 'どぅ')
      call t.add_map('xxa', 'ぁ')
      call t.add_map('xxi', 'ぃ')
      call t.add_map('xxu', 'ぅ')
      call t.add_map('xxe', 'ぇ')
      call t.add_map('xxo', 'ぉ')
      call t.add_map('xya', 'ゃ')
      call t.add_map('xyu', 'ゅ')
      call t.add_map('xyo', 'ょ')
      call t.add_map('xwa', 'ゎ')
      call t.add_map('xtsu', 'っ')
      call t.add_map('xtu', 'っ')
      call t.add_map(';', 'っ')
      call t.add_map('t;', 'っ')
      call t.add_map('kt', 'こと')
      call t.add_map('st', 'した')
      call t.add_map('tt', 'たち')
      call t.add_map('ht', 'ひと')
      call t.add_map('wt', 'わた')
      call t.add_map('mn', 'もの')
      call t.add_map('ms', 'ます')
      call t.add_map('ds', 'です')
      call t.add_map('km', 'かも')
      call t.add_map('tm', 'ため')
      call t.add_map('dm', 'でも')
      call t.add_map('kr', 'から')
      call t.add_map('sr', 'する')
      call t.add_map('tr', 'たら')
      call t.add_map('nr', 'なる')
      call t.add_map('yr', 'よる')
      call t.add_map('rr', 'られ')
      call t.add_map('zr', 'ざる')
      call t.add_map('mt', 'また')
      call t.add_map('tb', 'たび')
      call t.add_map('nb', 'ねば')
      call t.add_map('bt', 'びと')
      call t.add_map('gr', 'がら')
      call t.add_map('gt', 'ごと')
      call t.add_map('nt', 'にち')
      call t.add_map('dt', 'だち')
      call t.add_map('wr', 'われ')
      call eskk#register_mode_table('hira', t) "}}}
      let t = eskk#table#new('rom_to_kata*', 'rom_to_kata') "{{{
      call t.add_map('x[', '「')
      call t.add_map('_', '「')
      call t.add_map('z_', '『')
      call t.add_map('z(', '（')
      call t.add_map('z)', '）')
      call t.add_map('z{', '【')
      call t.add_map('z}', '】')
      call t.add_map('z ', '　')
      call t.add_map('z*', '※')
      call t.add_map('z0', '○')
      call t.add_map('z@', '◎')
      call t.add_map('xxh', '←')
      call t.add_map('xxj', '↓')
      call t.add_map('xxk', '↑')
      call t.add_map('xxl', '→')
      call t.add_map('''', 'ー')
      call t.add_map(':', 'ー')
      call t.add_map('z:', '゜')
      call t.add_map('z;', '゛')
      call t.add_map('a', 'ア')
      call t.add_map('i', 'イ')
      call t.add_map('u', 'ウ')
      call t.add_map('e', 'エ')
      call t.add_map('o', 'オ')
      call t.add_map('ka', 'カ')
      call t.add_map('ki', 'キ')
      call t.add_map('kf', 'キ')
      call t.add_map('ku', 'ク')
      call t.add_map('ke', 'ケ')
      call t.add_map('ko', 'コ')
      call t.add_map('sa', 'サ')
      call t.add_map('si', 'シ')
      call t.add_map('su', 'ス')
      call t.add_map('se', 'セ')
      call t.add_map('so', 'ソ')
      call t.add_map('ta', 'タ')
      call t.add_map('ti', 'チ')
      call t.add_map('tsu', 'ツ')
      call t.add_map('tu', 'ツ')
      call t.add_map('te', 'テ')
      call t.add_map('to', 'ト')
      call t.add_map('na', 'ナ')
      call t.add_map('ni', 'ニ')
      call t.add_map('nu', 'ヌ')
      call t.add_map('nf', 'ヌ')
      call t.add_map('ne', 'ネ')
      call t.add_map('no', 'ノ')
      call t.add_map('ha', 'ハ')
      call t.add_map('hi', 'ヒ')
      call t.add_map('hu', 'フ')
      call t.add_map('hf', 'フ')
      call t.add_map('he', 'ヘ')
      call t.add_map('ho', 'ホ')
      call t.add_map('fa', 'ファ')
      call t.add_map('fi', 'フィ')
      call t.add_map('fu', 'フ')
      call t.add_map('fe', 'フェ')
      call t.add_map('fo', 'フォ')
      call t.add_map('ma', 'マ')
      call t.add_map('mi', 'ミ')
      call t.add_map('mu', 'ム')
      call t.add_map('mf', 'ム')
      call t.add_map('me', 'メ')
      call t.add_map('mo', 'モ')
      call t.add_map('ya', 'ヤ')
      call t.add_map('yi', 'イ')
      call t.add_map('yu', 'ユ')
      call t.add_map('yf', 'ユ')
      call t.add_map('ye', 'イェ')
      call t.add_map('yo', 'ヨ')
      call t.add_map('ra', 'ラ')
      call t.add_map('ri', 'リ')
      call t.add_map('ru', 'ル')
      call t.add_map('re', 'レ')
      call t.add_map('ro', 'ロ')
      call t.add_map('wa', 'ワ')
      call t.add_map('wi', 'ヰ')
      call t.add_map('wu', 'ウ')
      call t.add_map('we', 'ヱ')
      call t.add_map('wo', 'ヲ')
      call t.add_map('q', 'ン')
      call t.add_map('kz', 'カン')
      call t.add_map('kn', 'カン')
      call t.add_map('kk', 'キン')
      call t.add_map('kj', 'クン')
      call t.add_map('kd', 'ケン')
      call t.add_map('kl', 'コン')
      call t.add_map('sz', 'サン')
      call t.add_map('sn', 'サン')
      call t.add_map('sk', 'シン')
      call t.add_map('sj', 'スン')
      call t.add_map('sd', 'セン')
      call t.add_map('sl', 'ソン')
      call t.add_map('tz', 'タン')
      call t.add_map('tn', 'タン')
      call t.add_map('tk', 'チン')
      call t.add_map('tj', 'ツン')
      call t.add_map('td', 'テン')
      call t.add_map('tl', 'トン')
      call t.add_map('nz', 'ナン')
      call t.add_map('nn', 'ン')
      call t.add_map('nk', 'ニン')
      call t.add_map('nj', 'ヌン')
      call t.add_map('nd', 'ネン')
      call t.add_map('nl', 'ノン')
      call t.add_map('hz', 'ハン')
      call t.add_map('hn', 'ハン')
      call t.add_map('hk', 'ヒン')
      call t.add_map('hj', 'フン')
      call t.add_map('hd', 'ヘン')
      call t.add_map('hl', 'ホン')
      call t.add_map('fz', 'ファン')
      call t.add_map('fn', 'ファン')
      call t.add_map('fk', 'フィン')
      call t.add_map('fj', 'フン')
      call t.add_map('fd', 'フェン')
      call t.add_map('fl', 'フォン')
      call t.add_map('mz', 'マン')
      call t.add_map('mk', 'ミン')
      call t.add_map('mj', 'ムン')
      call t.add_map('md', 'メン')
      call t.add_map('ml', 'モン')
      call t.add_map('yz', 'ヤン')
      call t.add_map('yn', 'ヤン')
      call t.add_map('yj', 'ユン')
      call t.add_map('yl', 'ヨン')
      call t.add_map('rz', 'ラン')
      call t.add_map('rn', 'ラン')
      call t.add_map('rk', 'リン')
      call t.add_map('rj', 'ルン')
      call t.add_map('rd', 'レン')
      call t.add_map('rl', 'ロン')
      call t.add_map('wz', 'ワン')
      call t.add_map('wn', 'ワン')
      call t.add_map('wk', 'ウィン')
      call t.add_map('wd', 'ウェン')
      call t.add_map('wl', 'ウォン')
      call t.add_map('kq', 'カイ')
      call t.add_map('kh', 'クウ')
      call t.add_map('kw', 'ケイ')
      call t.add_map('kp', 'コウ')
      call t.add_map('sq', 'サイ')
      call t.add_map('sh', 'スウ')
      call t.add_map('sw', 'セイ')
      call t.add_map('sp', 'ソウ')
      call t.add_map('tq', 'タイ')
      call t.add_map('th', 'ツウ')
      call t.add_map('tw', 'テイ')
      call t.add_map('tp', 'トウ')
      call t.add_map('nq', 'ナイ')
      call t.add_map('nh', 'ヌウ')
      call t.add_map('nw', 'ネイ')
      call t.add_map('np', 'ノウ')
      call t.add_map('hq', 'ハイ')
      call t.add_map('hh', 'フウ')
      call t.add_map('hw', 'ヘイ')
      call t.add_map('hp', 'ホウ')
      call t.add_map('fq', 'ファイ')
      call t.add_map('fh', 'フウ')
      call t.add_map('fw', 'フェイ')
      call t.add_map('fp', 'フォー')
      call t.add_map('mq', 'マイ')
      call t.add_map('mh', 'ムウ')
      call t.add_map('mw', 'メイ')
      call t.add_map('mp', 'モウ')
      call t.add_map('yq', 'ヤイ')
      call t.add_map('yh', 'ユウ')
      call t.add_map('yp', 'ヨウ')
      call t.add_map('rq', 'ライ')
      call t.add_map('rh', 'ルウ')
      call t.add_map('rw', 'レイ')
      call t.add_map('rp', 'ロウ')
      call t.add_map('wq', 'ワイ')
      call t.add_map('wp', 'ウォー')
      call t.add_map('ga', 'ガ')
      call t.add_map('gi', 'ギ')
      call t.add_map('gu', 'グ')
      call t.add_map('ge', 'ゲ')
      call t.add_map('go', 'ゴ')
      call t.add_map('za', 'ザ')
      call t.add_map('zi', 'ジ')
      call t.add_map('zu', 'ズ')
      call t.add_map('ze', 'ゼ')
      call t.add_map('zo', 'ゾ')
      call t.add_map('da', 'ダ')
      call t.add_map('di', 'ヂ')
      call t.add_map('du', 'ヅ')
      call t.add_map('de', 'デ')
      call t.add_map('df', 'デ')
      call t.add_map('do', 'ド')
      call t.add_map('ba', 'バ')
      call t.add_map('bi', 'ビ')
      call t.add_map('bu', 'ブ')
      call t.add_map('be', 'ベ')
      call t.add_map('bo', 'ボ')
      call t.add_map('pa', 'パ')
      call t.add_map('pi', 'ピ')
      call t.add_map('pu', 'プ')
      call t.add_map('pe', 'ペ')
      call t.add_map('po', 'ポ')
      call t.add_map('gz', 'ガン')
      call t.add_map('gn', 'ガン')
      call t.add_map('gk', 'ギン')
      call t.add_map('gj', 'グン')
      call t.add_map('gd', 'ゲン')
      call t.add_map('gl', 'ゴン')
      call t.add_map('zz', 'ザン')
      call t.add_map('zn', 'ザン')
      call t.add_map('zk', 'ジン')
      call t.add_map('zj', 'ズン')
      call t.add_map('zd', 'ゼン')
      call t.add_map('zl', 'ゾン')
      call t.add_map('dz', 'ダン')
      call t.add_map('dn', 'ダン')
      call t.add_map('dk', 'ヂン')
      call t.add_map('dj', 'ヅン')
      call t.add_map('dd', 'デン')
      call t.add_map('dl', 'ドン')
      call t.add_map('bz', 'バン')
      call t.add_map('bn', 'バン')
      call t.add_map('bk', 'ビン')
      call t.add_map('bj', 'ブン')
      call t.add_map('bd', 'ベン')
      call t.add_map('bl', 'ボン')
      call t.add_map('pz', 'パン')
      call t.add_map('pn', 'パン')
      call t.add_map('pk', 'ピン')
      call t.add_map('pj', 'プン')
      call t.add_map('pd', 'ペン')
      call t.add_map('pl', 'ポン')
      call t.add_map('gq', 'ガイ')
      call t.add_map('gh', 'グウ')
      call t.add_map('gw', 'ゲイ')
      call t.add_map('gp', 'ゴウ')
      call t.add_map('zq', 'ザイ')
      call t.add_map('zh', 'ズウ')
      call t.add_map('zw', 'ゼイ')
      call t.add_map('zp', 'ゾウ')
      call t.add_map('dq', 'ダイ')
      call t.add_map('dh', 'ヅウ')
      call t.add_map('dw', 'デイ')
      call t.add_map('dp', 'ドウ')
      call t.add_map('bq', 'バイ')
      call t.add_map('bh', 'ブウ')
      call t.add_map('bw', 'ベイ')
      call t.add_map('bp', 'ボウ')
      call t.add_map('pq', 'パイ')
      call t.add_map('ph', 'プウ')
      call t.add_map('pw', 'ペイ')
      call t.add_map('pp', 'ポウ')
      call t.add_map('zc', 'ザ')
      call t.add_map('zv', 'ザイ')
      call t.add_map('zx', 'ゼイ')
      call t.add_map('kya', 'キャ')
      call t.add_map('kyi', 'キィ')
      call t.add_map('kyu', 'キュ')
      call t.add_map('kye', 'キェ')
      call t.add_map('kyo', 'キョ')
      call t.add_map('kga', 'キャ')
      call t.add_map('kgi', 'イ')
      call t.add_map('kgu', 'キュ')
      call t.add_map('kge', 'キェ')
      call t.add_map('kgo', 'キョ')
      call t.add_map('sya', 'シャ')
      call t.add_map('syi', 'シィ')
      call t.add_map('syu', 'シュ')
      call t.add_map('sye', 'シェ')
      call t.add_map('syo', 'ショ')
      call t.add_map('xa', 'シャ')
      call t.add_map('xi', 'シ')
      call t.add_map('xu', 'シュ')
      call t.add_map('xe', 'シェ')
      call t.add_map('xo', 'ショ')
      call t.add_map('tya', 'チャ')
      call t.add_map('tyi', 'チィ')
      call t.add_map('tyu', 'チュ')
      call t.add_map('tye', 'チェ')
      call t.add_map('tyo', 'チョ')
      call t.add_map('ca', 'チャ')
      call t.add_map('ci', 'チ')
      call t.add_map('cu', 'チュ')
      call t.add_map('ce', 'チェ')
      call t.add_map('co', 'チョ')
      call t.add_map('nya', 'ニャ')
      call t.add_map('nyi', 'ニィ')
      call t.add_map('nyu', 'ニュ')
      call t.add_map('nye', 'ニェ')
      call t.add_map('nyo', 'ニョ')
      call t.add_map('nga', 'ニャ')
      call t.add_map('ngi', 'イ')
      call t.add_map('ngu', 'ニュ')
      call t.add_map('nge', 'ニェ')
      call t.add_map('ngo', 'ニョ')
      call t.add_map('hya', 'ヒャ')
      call t.add_map('hyi', 'ヒィ')
      call t.add_map('hyu', 'ヒュ')
      call t.add_map('hye', 'ヒェ')
      call t.add_map('hyo', 'ヒョ')
      call t.add_map('hga', 'ヒャ')
      call t.add_map('hgi', 'イ')
      call t.add_map('hgu', 'ヒュ')
      call t.add_map('hge', 'ヒェ')
      call t.add_map('hgo', 'ヒョ')
      call t.add_map('mya', 'ミャ')
      call t.add_map('myi', 'ミィ')
      call t.add_map('myu', 'ミュ')
      call t.add_map('mye', 'ミェ')
      call t.add_map('myo', 'ミョ')
      call t.add_map('mga', 'ミャ')
      call t.add_map('mgi', 'イ')
      call t.add_map('mgu', 'ミュ')
      call t.add_map('mge', 'ミェ')
      call t.add_map('mgo', 'ミョ')
      call t.add_map('rya', 'リャ')
      call t.add_map('ryi', 'リィ')
      call t.add_map('ryu', 'リュ')
      call t.add_map('rye', 'リェ')
      call t.add_map('ryo', 'リョ')
      call t.add_map('kyz', 'キャン')
      call t.add_map('kyn', 'キャン')
      call t.add_map('kyj', 'キュン')
      call t.add_map('kyd', 'キェン')
      call t.add_map('kyl', 'キョン')
      call t.add_map('kgz', 'キャン')
      call t.add_map('kgn', 'キャン')
      call t.add_map('kgj', 'キュン')
      call t.add_map('kgd', 'キェン')
      call t.add_map('kgl', 'キョン')
      call t.add_map('syz', 'シャン')
      call t.add_map('syn', 'シャン')
      call t.add_map('syj', 'シュン')
      call t.add_map('syd', 'シェン')
      call t.add_map('syl', 'ション')
      call t.add_map('xz', 'シャン')
      call t.add_map('xn', 'シャン')
      call t.add_map('xj', 'シュン')
      call t.add_map('xd', 'シェン')
      call t.add_map('xl', 'ション')
      call t.add_map('tyz', 'チャン')
      call t.add_map('tyn', 'チャン')
      call t.add_map('tyj', 'チュン')
      call t.add_map('tyd', 'チェン')
      call t.add_map('tyl', 'チョン')
      call t.add_map('cz', 'チャン')
      call t.add_map('cn', 'チャン')
      call t.add_map('cj', 'チュン')
      call t.add_map('cd', 'チェン')
      call t.add_map('cl', 'チョン')
      call t.add_map('nyz', 'ニャン')
      call t.add_map('nyn', 'ニャン')
      call t.add_map('nyj', 'ニュン')
      call t.add_map('nyd', 'ニェン')
      call t.add_map('nyl', 'ニョン')
      call t.add_map('ngz', 'ニャン')
      call t.add_map('ngn', 'ニャン')
      call t.add_map('ngj', 'ニュン')
      call t.add_map('ngd', 'ニェン')
      call t.add_map('ngl', 'ニョン')
      call t.add_map('hyz', 'ヒャン')
      call t.add_map('hyn', 'ヒャン')
      call t.add_map('hyj', 'ヒュン')
      call t.add_map('hyd', 'ヒェン')
      call t.add_map('hyl', 'ヒョン')
      call t.add_map('hgz', 'ヒャン')
      call t.add_map('hgn', 'ヒャン')
      call t.add_map('hgj', 'ヒュン')
      call t.add_map('hgd', 'ヒェン')
      call t.add_map('hgl', 'ヒョン')
      call t.add_map('myz', 'ミャン')
      call t.add_map('myn', 'ミャン')
      call t.add_map('myj', 'ミュン')
      call t.add_map('myd', 'ミェン')
      call t.add_map('myl', 'ミョン')
      call t.add_map('mgz', 'ミャン')
      call t.add_map('mgn', 'ミャン')
      call t.add_map('mgj', 'ミュン')
      call t.add_map('mgd', 'ミェン')
      call t.add_map('mgl', 'ミョン')
      call t.add_map('ryz', 'リャン')
      call t.add_map('ryn', 'リャン')
      call t.add_map('ryj', 'リュン')
      call t.add_map('ryd', 'リェン')
      call t.add_map('ryl', 'リョン')
      call t.add_map('kyq', 'キャイ')
      call t.add_map('kyh', 'キュウ')
      call t.add_map('kyw', 'キェイ')
      call t.add_map('kyp', 'キョウ')
      call t.add_map('kgq', 'キャイ')
      call t.add_map('kgh', 'キュウ')
      call t.add_map('kgw', 'キェイ')
      call t.add_map('kgp', 'キョウ')
      call t.add_map('syq', 'シャイ')
      call t.add_map('syh', 'シュウ')
      call t.add_map('syw', 'シェイ')
      call t.add_map('syp', 'ショウ')
      call t.add_map('xq', 'シャイ')
      call t.add_map('xh', 'シュウ')
      call t.add_map('xw', 'シェイ')
      call t.add_map('xp', 'ショウ')
      call t.add_map('tyq', 'チャイ')
      call t.add_map('tyh', 'チュウ')
      call t.add_map('tyw', 'チェイ')
      call t.add_map('typ', 'チョウ')
      call t.add_map('cq', 'チャイ')
      call t.add_map('ch', 'チュウ')
      call t.add_map('cw', 'チェイ')
      call t.add_map('cp', 'チョウ')
      call t.add_map('nyq', 'ニャイ')
      call t.add_map('nyh', 'ニュウ')
      call t.add_map('nyw', 'ニェイ')
      call t.add_map('nyp', 'ニョウ')
      call t.add_map('ngq', 'ニャイ')
      call t.add_map('ngh', 'ニュウ')
      call t.add_map('ngw', 'ニェイ')
      call t.add_map('ngp', 'ニョウ')
      call t.add_map('hyq', 'ヒャイ')
      call t.add_map('hyh', 'ヒュウ')
      call t.add_map('hyw', 'ヒェイ')
      call t.add_map('hyp', 'ヒョウ')
      call t.add_map('hgq', 'ヒャイ')
      call t.add_map('hgh', 'ヒュウ')
      call t.add_map('hgw', 'ヒェイ')
      call t.add_map('hgp', 'ヒョウ')
      call t.add_map('myq', 'ミャイ')
      call t.add_map('myh', 'ミュウ')
      call t.add_map('myw', 'ミェイ')
      call t.add_map('myp', 'ミョウ')
      call t.add_map('mgq', 'ミャイ')
      call t.add_map('mgh', 'ミュウ')
      call t.add_map('mgw', 'ミェイ')
      call t.add_map('mgp', 'ミョウ')
      call t.add_map('ryq', 'リャイ')
      call t.add_map('ryh', 'リュウ')
      call t.add_map('ryw', 'リェイ')
      call t.add_map('ryp', 'リョウ')
      call t.add_map('gya', 'ギャ')
      call t.add_map('gyu', 'ギュ')
      call t.add_map('gye', 'ギェ')
      call t.add_map('gyo', 'ギョ')
      call t.add_map('zya', 'ジャ')
      call t.add_map('zyu', 'ジュ')
      call t.add_map('zye', 'ジェ')
      call t.add_map('zyo', 'ジョ')
      call t.add_map('jya', 'ジャ')
      call t.add_map('jyu', 'ジュ')
      call t.add_map('jye', 'ジェ')
      call t.add_map('jyo', 'ジョ')
      call t.add_map('ja', 'ジャ')
      call t.add_map('ji', 'ジ')
      call t.add_map('ju', 'ジュ')
      call t.add_map('je', 'ジェ')
      call t.add_map('jo', 'ジョ')
      call t.add_map('bya', 'ビャ')
      call t.add_map('byu', 'ビュ')
      call t.add_map('bye', 'ビェ')
      call t.add_map('byo', 'ビョ')
      call t.add_map('pya', 'ピャ')
      call t.add_map('pyu', 'ピュ')
      call t.add_map('pye', 'ピェ')
      call t.add_map('pyo', 'ピョ')
      call t.add_map('pga', 'ピャ')
      call t.add_map('pgi', 'イ')
      call t.add_map('pgu', 'ピュ')
      call t.add_map('pge', 'ピェ')
      call t.add_map('pgo', 'ピョ')
      call t.add_map('gyz', 'ギャン')
      call t.add_map('gyn', 'ギャン')
      call t.add_map('gyj', 'ギュン')
      call t.add_map('gyd', 'ギェン')
      call t.add_map('gyl', 'ギョン')
      call t.add_map('zyz', 'ジャン')
      call t.add_map('zyn', 'ジャン')
      call t.add_map('zyj', 'ジュン')
      call t.add_map('zyd', 'ジェン')
      call t.add_map('zyl', 'ジョン')
      call t.add_map('jz', 'ジャン')
      call t.add_map('jn', 'ジャン')
      call t.add_map('jk', 'ジン')
      call t.add_map('jj', 'ジュン')
      call t.add_map('jd', 'ジェン')
      call t.add_map('jl', 'ジョン')
      call t.add_map('byz', 'ビャン')
      call t.add_map('byn', 'ビャン')
      call t.add_map('byj', 'ビュン')
      call t.add_map('byd', 'ビェン')
      call t.add_map('byl', 'ビョン')
      call t.add_map('pyz', 'ピャン')
      call t.add_map('pyn', 'ピャン')
      call t.add_map('pyj', 'ピュン')
      call t.add_map('pyd', 'ピェン')
      call t.add_map('pyl', 'ピョン')
      call t.add_map('pgz', 'ピャン')
      call t.add_map('pgn', 'ピャン')
      call t.add_map('pgj', 'ピュン')
      call t.add_map('pgd', 'ピェン')
      call t.add_map('pgl', 'ピョン')
      call t.add_map('gyq', 'ギャイ')
      call t.add_map('gyh', 'ギュウ')
      call t.add_map('gyw', 'ギェイ')
      call t.add_map('gyp', 'ギョウ')
      call t.add_map('zyq', 'ジャイ')
      call t.add_map('zyh', 'ジュウ')
      call t.add_map('zyw', 'ジェイ')
      call t.add_map('zyp', 'ジョウ')
      call t.add_map('jq', 'ジャイ')
      call t.add_map('jh', 'ジュウ')
      call t.add_map('jw', 'ジェイ')
      call t.add_map('jp', 'ジョウ')
      call t.add_map('byq', 'ビャイ')
      call t.add_map('byh', 'ビュウ')
      call t.add_map('byw', 'ビェイ')
      call t.add_map('byp', 'ビョウ')
      call t.add_map('pyq', 'ピャイ')
      call t.add_map('pyh', 'ピュウ')
      call t.add_map('pyw', 'ピェイ')
      call t.add_map('pyp', 'ピョウ')
      call t.add_map('pgq', 'ピャイ')
      call t.add_map('pgh', 'ピュウ')
      call t.add_map('pgw', 'ピェイ')
      call t.add_map('pgp', 'ピョウ')
      call t.add_map('va', 'ヴァ')
      call t.add_map('vi', 'ヴィ')
      call t.add_map('vu', 'ヴ')
      call t.add_map('ve', 'ヴェ')
      call t.add_map('vo', 'ヴォ')
      call t.add_map('tgi', 'ティ')
      call t.add_map('tgu', 'トゥ')
      call t.add_map('dci', 'ディ')
      call t.add_map('dcu', 'ドゥ')
      call t.add_map('xxa', 'ァ')
      call t.add_map('xxi', 'ィ')
      call t.add_map('xxu', 'ゥ')
      call t.add_map('xxe', 'ェ')
      call t.add_map('xxo', 'ォ')
      call t.add_map('xya', 'ャ')
      call t.add_map('xyu', 'ュ')
      call t.add_map('xyo', 'ョ')
      call t.add_map('xwa', 'ヮ')
      call t.add_map('xtsu', 'ッ')
      call t.add_map('xtu', 'ッ')
      call t.add_map(';', 'ッ')
      call t.add_map('t;', 'ッ')
      call t.add_map('kt', 'コト')
      call t.add_map('st', 'シタ')
      call t.add_map('tt', 'タチ')
      call t.add_map('ht', 'ヒト')
      call t.add_map('wt', 'ワタ')
      call t.add_map('mn', 'モノ')
      call t.add_map('ms', 'マス')
      call t.add_map('ds', 'デス')
      call t.add_map('km', 'カモ')
      call t.add_map('tm', 'タメ')
      call t.add_map('dm', 'デモ')
      call t.add_map('kr', 'カラ')
      call t.add_map('sr', 'スル')
      call t.add_map('tr', 'タラ')
      call t.add_map('nr', 'ナル')
      call t.add_map('yr', 'ヨル')
      call t.add_map('rr', 'ラレ')
      call t.add_map('zr', 'ザル')
      call t.add_map('mt', 'マタ')
      call t.add_map('tb', 'タビ')
      call t.add_map('nb', 'ネバ')
      call t.add_map('bt', 'ビト')
      call t.add_map('gr', 'ガラ')
      call t.add_map('gt', 'ゴト')
      call t.add_map('nt', 'ニチ')
      call t.add_map('dt', 'ダチ')
      call t.add_map('wr', 'ワレ')
      call eskk#register_mode_table('kata', t) "}}}
      let t = eskk#table#new('rom_to_hankata*', 'rom_to_hankata') "{{{
      call t.add_map('x[', '｢')
      call t.add_map('_', '｢')
      call t.add_map('z_', '『')
      call t.add_map('xxh', '←')
      call t.add_map('xxj', '↓')
      call t.add_map('xxk', '↑')
      call t.add_map('xxl', '→')
      call t.add_map('''', 'ｰ')
      call t.add_map(':', 'ｰ')
      call t.add_map('z:', 'ﾟ')
      call t.add_map('z;', 'ﾞ')
      call t.add_map('a', 'ｱ')
      call t.add_map('i', 'ｲ')
      call t.add_map('u', 'ｳ')
      call t.add_map('e', 'ｴ')
      call t.add_map('o', 'ｵ')
      call t.add_map('ka', 'ｶ')
      call t.add_map('ki', 'ｷ')
      call t.add_map('kf', 'ｷ')
      call t.add_map('ku', 'ｸ')
      call t.add_map('ke', 'ｹ')
      call t.add_map('ko', 'ｺ')
      call t.add_map('sa', 'ｻ')
      call t.add_map('si', 'ｼ')
      call t.add_map('su', 'ｽ')
      call t.add_map('se', 'ｾ')
      call t.add_map('so', 'ｿ')
      call t.add_map('ta', 'ﾀ')
      call t.add_map('ti', 'ﾁ')
      call t.add_map('tsu', 'ﾂ')
      call t.add_map('tu', 'ﾂ')
      call t.add_map('te', 'ﾃ')
      call t.add_map('to', 'ﾄ')
      call t.add_map('na', 'ﾅ')
      call t.add_map('ni', 'ﾆ')
      call t.add_map('nu', 'ﾇ')
      call t.add_map('nf', 'ﾇ')
      call t.add_map('ne', 'ﾈ')
      call t.add_map('no', 'ﾉ')
      call t.add_map('ha', 'ﾊ')
      call t.add_map('hi', 'ﾋ')
      call t.add_map('hu', 'ﾌ')
      call t.add_map('hf', 'ﾌ')
      call t.add_map('he', 'ﾍ')
      call t.add_map('ho', 'ﾎ')
      call t.add_map('fa', 'ﾌｧ')
      call t.add_map('fi', 'ﾌｨ')
      call t.add_map('fu', 'ﾌ')
      call t.add_map('fe', 'ﾌｪ')
      call t.add_map('fo', 'ﾌｫ')
      call t.add_map('ma', 'ﾏ')
      call t.add_map('mi', 'ﾐ')
      call t.add_map('mu', 'ﾑ')
      call t.add_map('mf', 'ﾑ')
      call t.add_map('me', 'ﾒ')
      call t.add_map('mo', 'ﾓ')
      call t.add_map('ya', 'ﾔ')
      call t.add_map('yi', 'ｲ')
      call t.add_map('yu', 'ﾕ')
      call t.add_map('yf', 'ﾕ')
      call t.add_map('ye', 'ｲｪ')
      call t.add_map('yo', 'ﾖ')
      call t.add_map('ra', 'ﾗ')
      call t.add_map('ri', 'ﾘ')
      call t.add_map('ru', 'ﾙ')
      call t.add_map('re', 'ﾚ')
      call t.add_map('ro', 'ﾛ')
      call t.add_map('wa', 'ﾜ')
      call t.add_map('wi', 'ヰ')
      call t.add_map('wu', 'ｳ')
      call t.add_map('we', 'ヱ')
      call t.add_map('wo', 'ｦ')
      call t.add_map('q', 'ﾝ')
      call t.add_map('kz', 'ｶﾝ')
      call t.add_map('kn', 'ｶﾝ')
      call t.add_map('kk', 'ｷﾝ')
      call t.add_map('kj', 'ｸﾝ')
      call t.add_map('kd', 'ｹﾝ')
      call t.add_map('kl', 'ｺﾝ')
      call t.add_map('sz', 'ｻﾝ')
      call t.add_map('sn', 'ｻﾝ')
      call t.add_map('sk', 'ｼﾝ')
      call t.add_map('sj', 'ｽﾝ')
      call t.add_map('sd', 'ｾﾝ')
      call t.add_map('sl', 'ｿﾝ')
      call t.add_map('tz', 'ﾀﾝ')
      call t.add_map('tn', 'ﾀﾝ')
      call t.add_map('tk', 'ﾁﾝ')
      call t.add_map('tj', 'ﾂﾝ')
      call t.add_map('td', 'ﾃﾝ')
      call t.add_map('tl', 'ﾄﾝ')
      call t.add_map('nz', 'ﾅﾝ')
      call t.add_map('nn', 'ﾝ')
      call t.add_map('nk', 'ﾆﾝ')
      call t.add_map('nj', 'ﾇﾝ')
      call t.add_map('nd', 'ﾈﾝ')
      call t.add_map('nl', 'ﾉﾝ')
      call t.add_map('hz', 'ﾊﾝ')
      call t.add_map('hn', 'ﾊﾝ')
      call t.add_map('hk', 'ﾋﾝ')
      call t.add_map('hj', 'ﾌﾝ')
      call t.add_map('hd', 'ﾍﾝ')
      call t.add_map('hl', 'ﾎﾝ')
      call t.add_map('fz', 'ﾌｧﾝ')
      call t.add_map('fn', 'ﾌｧﾝ')
      call t.add_map('fk', 'ﾌｨﾝ')
      call t.add_map('fj', 'ﾌﾝ')
      call t.add_map('fd', 'ﾌｪﾝ')
      call t.add_map('fl', 'ﾌｫﾝ')
      call t.add_map('mz', 'ﾏﾝ')
      call t.add_map('mk', 'ﾐﾝ')
      call t.add_map('mj', 'ﾑﾝ')
      call t.add_map('md', 'ﾒﾝ')
      call t.add_map('ml', 'ﾓﾝ')
      call t.add_map('yz', 'ﾔﾝ')
      call t.add_map('yn', 'ﾔﾝ')
      call t.add_map('yj', 'ﾕﾝ')
      call t.add_map('yl', 'ﾖﾝ')
      call t.add_map('rz', 'ﾗﾝ')
      call t.add_map('rn', 'ﾗﾝ')
      call t.add_map('rk', 'ﾘﾝ')
      call t.add_map('rj', 'ﾙﾝ')
      call t.add_map('rd', 'ﾚﾝ')
      call t.add_map('rl', 'ﾛﾝ')
      call t.add_map('wz', 'ﾜﾝ')
      call t.add_map('wn', 'ﾜﾝ')
      call t.add_map('wk', 'ｳｨﾝ')
      call t.add_map('wd', 'ｳｪﾝ')
      call t.add_map('wl', 'ｳｫﾝ')
      call t.add_map('kq', 'ｶｲ')
      call t.add_map('kh', 'ｸｳ')
      call t.add_map('kw', 'ｹｲ')
      call t.add_map('kp', 'ｺｳ')
      call t.add_map('sq', 'ｻｲ')
      call t.add_map('sh', 'ｽｳ')
      call t.add_map('sw', 'ｾｲ')
      call t.add_map('sp', 'ｿｳ')
      call t.add_map('tq', 'ﾀｲ')
      call t.add_map('th', 'ﾂｳ')
      call t.add_map('tw', 'ﾃｲ')
      call t.add_map('tp', 'ﾄｳ')
      call t.add_map('nq', 'ﾅｲ')
      call t.add_map('nh', 'ﾇｳ')
      call t.add_map('nw', 'ﾈｲ')
      call t.add_map('np', 'ﾉｳ')
      call t.add_map('hq', 'ﾊｲ')
      call t.add_map('hh', 'ﾌｳ')
      call t.add_map('hw', 'ﾍｲ')
      call t.add_map('hp', 'ﾎｳ')
      call t.add_map('fq', 'ﾌｧｲ')
      call t.add_map('fh', 'ﾌｳ')
      call t.add_map('fw', 'ﾌｪｲ')
      call t.add_map('fp', 'ﾌｫｰ')
      call t.add_map('mq', 'ﾏｲ')
      call t.add_map('mh', 'ﾑｳ')
      call t.add_map('mw', 'ﾒｲ')
      call t.add_map('mp', 'ﾓｳ')
      call t.add_map('yq', 'ﾔｲ')
      call t.add_map('yh', 'ﾕｳ')
      call t.add_map('yp', 'ﾖｳ')
      call t.add_map('rq', 'ﾗｲ')
      call t.add_map('rh', 'ﾙｳ')
      call t.add_map('rw', 'ﾚｲ')
      call t.add_map('rp', 'ﾛｳ')
      call t.add_map('wq', 'ﾜｲ')
      call t.add_map('wp', 'ｳｫｰ')
      call t.add_map('ga', 'ｶﾞ')
      call t.add_map('gi', 'ｷﾞ')
      call t.add_map('gu', 'ｸﾞ')
      call t.add_map('ge', 'ｹﾞ')
      call t.add_map('go', 'ｺﾞ')
      call t.add_map('za', 'ｻﾞ')
      call t.add_map('zi', 'ｼﾞ')
      call t.add_map('zu', 'ｽﾞ')
      call t.add_map('ze', 'ｾﾞ')
      call t.add_map('zo', 'ｿﾞ')
      call t.add_map('da', 'ﾀﾞ')
      call t.add_map('di', 'ﾁﾞ')
      call t.add_map('du', 'ﾂﾞ')
      call t.add_map('de', 'ﾃﾞ')
      call t.add_map('df', 'ﾃﾞ')
      call t.add_map('do', 'ﾄﾞ')
      call t.add_map('ba', 'ﾊﾞ')
      call t.add_map('bi', 'ﾋﾞ')
      call t.add_map('bu', 'ﾌﾞ')
      call t.add_map('be', 'ﾍﾞ')
      call t.add_map('bo', 'ﾎﾞ')
      call t.add_map('pa', 'ﾊﾟ')
      call t.add_map('pi', 'ﾋﾟ')
      call t.add_map('pu', 'ﾌﾟ')
      call t.add_map('pe', 'ﾍﾟ')
      call t.add_map('po', 'ﾎﾟ')
      call t.add_map('gz', 'ｶﾞﾝ')
      call t.add_map('gn', 'ｶﾞﾝ')
      call t.add_map('gk', 'ｷﾞﾝ')
      call t.add_map('gj', 'ｸﾞﾝ')
      call t.add_map('gd', 'ｹﾞﾝ')
      call t.add_map('gl', 'ｺﾞﾝ')
      call t.add_map('zz', 'ｻﾞﾝ')
      call t.add_map('zn', 'ｻﾞﾝ')
      call t.add_map('zk', 'ｼﾞﾝ')
      call t.add_map('zj', 'ｽﾞﾝ')
      call t.add_map('zd', 'ｾﾞﾝ')
      call t.add_map('zl', 'ｿﾞﾝ')
      call t.add_map('dz', 'ﾀﾞﾝ')
      call t.add_map('dn', 'ﾀﾞﾝ')
      call t.add_map('dk', 'ﾁﾞﾝ')
      call t.add_map('dj', 'ﾂﾞﾝ')
      call t.add_map('dd', 'ﾃﾞﾝ')
      call t.add_map('dl', 'ﾄﾞﾝ')
      call t.add_map('bz', 'ﾊﾞﾝ')
      call t.add_map('bn', 'ﾊﾞﾝ')
      call t.add_map('bk', 'ﾋﾞﾝ')
      call t.add_map('bj', 'ﾌﾞﾝ')
      call t.add_map('bd', 'ﾍﾞﾝ')
      call t.add_map('bl', 'ﾎﾞﾝ')
      call t.add_map('pz', 'ﾊﾟﾝ')
      call t.add_map('pn', 'ﾊﾟﾝ')
      call t.add_map('pk', 'ﾋﾟﾝ')
      call t.add_map('pj', 'ﾌﾟﾝ')
      call t.add_map('pd', 'ﾍﾟﾝ')
      call t.add_map('pl', 'ﾎﾟﾝ')
      call t.add_map('gq', 'ｶﾞｲ')
      call t.add_map('gh', 'ｸﾞｳ')
      call t.add_map('gw', 'ｹﾞｲ')
      call t.add_map('gp', 'ｺﾞｳ')
      call t.add_map('zq', 'ｻﾞｲ')
      call t.add_map('zh', 'ｽﾞｳ')
      call t.add_map('zw', 'ｾﾞｲ')
      call t.add_map('zp', 'ｿﾞｳ')
      call t.add_map('dq', 'ﾀﾞｲ')
      call t.add_map('dh', 'ﾂﾞｳ')
      call t.add_map('dw', 'ﾃﾞｲ')
      call t.add_map('dp', 'ﾄﾞｳ')
      call t.add_map('bq', 'ﾊﾞｲ')
      call t.add_map('bh', 'ﾌﾞｳ')
      call t.add_map('bw', 'ﾍﾞｲ')
      call t.add_map('bp', 'ﾎﾞｳ')
      call t.add_map('pq', 'ﾊﾟｲ')
      call t.add_map('ph', 'ﾌﾟｳ')
      call t.add_map('pw', 'ﾍﾟｲ')
      call t.add_map('pp', 'ﾎﾟｳ')
      call t.add_map('zc', 'ｻﾞ')
      call t.add_map('zv', 'ｻﾞｲ')
      call t.add_map('zx', 'ｾﾞｲ')
      call t.add_map('kya', 'ｷｬ')
      call t.add_map('kyi', 'ｷｨ')
      call t.add_map('kyu', 'ｷｭ')
      call t.add_map('kye', 'ｷｪ')
      call t.add_map('kyo', 'ｷｮ')
      call t.add_map('kga', 'ｷｬ')
      call t.add_map('kgi', 'ｲ')
      call t.add_map('kgu', 'ｷｭ')
      call t.add_map('kge', 'ｷｪ')
      call t.add_map('kgo', 'ｷｮ')
      call t.add_map('sya', 'ｼｬ')
      call t.add_map('syi', 'ｼｨ')
      call t.add_map('syu', 'ｼｭ')
      call t.add_map('sye', 'ｼｪ')
      call t.add_map('syo', 'ｼｮ')
      call t.add_map('xa', 'ｼｬ')
      call t.add_map('xi', 'ｼ')
      call t.add_map('xu', 'ｼｭ')
      call t.add_map('xe', 'ｼｪ')
      call t.add_map('xo', 'ｼｮ')
      call t.add_map('tya', 'ﾁｬ')
      call t.add_map('tyi', 'ﾁｨ')
      call t.add_map('tyu', 'ﾁｭ')
      call t.add_map('tye', 'ﾁｪ')
      call t.add_map('tyo', 'ﾁｮ')
      call t.add_map('ca', 'ﾁｬ')
      call t.add_map('ci', 'ﾁ')
      call t.add_map('cu', 'ﾁｭ')
      call t.add_map('ce', 'ﾁｪ')
      call t.add_map('co', 'ﾁｮ')
      call t.add_map('nya', 'ﾆｬ')
      call t.add_map('nyi', 'ﾆｨ')
      call t.add_map('nyu', 'ﾆｭ')
      call t.add_map('nye', 'ﾆｪ')
      call t.add_map('nyo', 'ﾆｮ')
      call t.add_map('nga', 'ﾆｬ')
      call t.add_map('ngi', 'ｲ')
      call t.add_map('ngu', 'ﾆｭ')
      call t.add_map('nge', 'ﾆｪ')
      call t.add_map('ngo', 'ﾆｮ')
      call t.add_map('hya', 'ﾋｬ')
      call t.add_map('hyi', 'ﾋｨ')
      call t.add_map('hyu', 'ﾋｭ')
      call t.add_map('hye', 'ﾋｪ')
      call t.add_map('hyo', 'ﾋｮ')
      call t.add_map('hga', 'ﾋｬ')
      call t.add_map('hgi', 'ｲ')
      call t.add_map('hgu', 'ﾋｭ')
      call t.add_map('hge', 'ﾋｪ')
      call t.add_map('hgo', 'ﾋｮ')
      call t.add_map('mya', 'ﾐｬ')
      call t.add_map('myi', 'ﾐｨ')
      call t.add_map('myu', 'ﾐｭ')
      call t.add_map('mye', 'ﾐｪ')
      call t.add_map('myo', 'ﾐｮ')
      call t.add_map('mga', 'ﾐｬ')
      call t.add_map('mgi', 'ｲ')
      call t.add_map('mgu', 'ﾐｭ')
      call t.add_map('mge', 'ﾐｪ')
      call t.add_map('mgo', 'ﾐｮ')
      call t.add_map('rya', 'ﾘｬ')
      call t.add_map('ryi', 'ﾘｨ')
      call t.add_map('ryu', 'ﾘｭ')
      call t.add_map('rye', 'ﾘｪ')
      call t.add_map('ryo', 'ﾘｮ')
      call t.add_map('kyz', 'ｷｬﾝ')
      call t.add_map('kyn', 'ｷｬﾝ')
      call t.add_map('kyj', 'ｷｭﾝ')
      call t.add_map('kyd', 'ｷｪﾝ')
      call t.add_map('kyl', 'ｷｮﾝ')
      call t.add_map('kgz', 'ｷｬﾝ')
      call t.add_map('kgn', 'ｷｬﾝ')
      call t.add_map('kgj', 'ｷｭﾝ')
      call t.add_map('kgd', 'ｷｪﾝ')
      call t.add_map('kgl', 'ｷｮﾝ')
      call t.add_map('syz', 'ｼｬﾝ')
      call t.add_map('syn', 'ｼｬﾝ')
      call t.add_map('syj', 'ｼｭﾝ')
      call t.add_map('syd', 'ｼｪﾝ')
      call t.add_map('syl', 'ｼｮﾝ')
      call t.add_map('xz', 'ｼｬﾝ')
      call t.add_map('xn', 'ｼｬﾝ')
      call t.add_map('xj', 'ｼｭﾝ')
      call t.add_map('xd', 'ｼｪﾝ')
      call t.add_map('xl', 'ｼｮﾝ')
      call t.add_map('tyz', 'ﾁｬﾝ')
      call t.add_map('tyn', 'ﾁｬﾝ')
      call t.add_map('tyj', 'ﾁｭﾝ')
      call t.add_map('tyd', 'ﾁｪﾝ')
      call t.add_map('tyl', 'ﾁｮﾝ')
      call t.add_map('cz', 'ﾁｬﾝ')
      call t.add_map('cn', 'ﾁｬﾝ')
      call t.add_map('cj', 'ﾁｭﾝ')
      call t.add_map('cd', 'ﾁｪﾝ')
      call t.add_map('cl', 'ﾁｮﾝ')
      call t.add_map('nyz', 'ﾆｬﾝ')
      call t.add_map('nyn', 'ﾆｬﾝ')
      call t.add_map('nyj', 'ﾆｭﾝ')
      call t.add_map('nyd', 'ﾆｪﾝ')
      call t.add_map('nyl', 'ﾆｮﾝ')
      call t.add_map('ngz', 'ﾆｬﾝ')
      call t.add_map('ngn', 'ﾆｬﾝ')
      call t.add_map('ngj', 'ﾆｭﾝ')
      call t.add_map('ngd', 'ﾆｪﾝ')
      call t.add_map('ngl', 'ﾆｮﾝ')
      call t.add_map('hyz', 'ﾋｬﾝ')
      call t.add_map('hyn', 'ﾋｬﾝ')
      call t.add_map('hyj', 'ﾋｭﾝ')
      call t.add_map('hyd', 'ﾋｪﾝ')
      call t.add_map('hyl', 'ﾋｮﾝ')
      call t.add_map('hgz', 'ﾋｬﾝ')
      call t.add_map('hgn', 'ﾋｬﾝ')
      call t.add_map('hgj', 'ﾋｭﾝ')
      call t.add_map('hgd', 'ﾋｪﾝ')
      call t.add_map('hgl', 'ﾋｮﾝ')
      call t.add_map('myz', 'ﾐｬﾝ')
      call t.add_map('myn', 'ﾐｬﾝ')
      call t.add_map('myj', 'ﾐｭﾝ')
      call t.add_map('myd', 'ﾐｪﾝ')
      call t.add_map('myl', 'ﾐｮﾝ')
      call t.add_map('mgz', 'ﾐｬﾝ')
      call t.add_map('mgn', 'ﾐｬﾝ')
      call t.add_map('mgj', 'ﾐｭﾝ')
      call t.add_map('mgd', 'ﾐｪﾝ')
      call t.add_map('mgl', 'ﾐｮﾝ')
      call t.add_map('ryz', 'ﾘｬﾝ')
      call t.add_map('ryn', 'ﾘｬﾝ')
      call t.add_map('ryj', 'ﾘｭﾝ')
      call t.add_map('ryd', 'ﾘｪﾝ')
      call t.add_map('ryl', 'ﾘｮﾝ')
      call t.add_map('kyq', 'ｷｬｲ')
      call t.add_map('kyh', 'ｷｭｳ')
      call t.add_map('kyw', 'ｷｪｲ')
      call t.add_map('kyp', 'ｷｮｳ')
      call t.add_map('kgq', 'ｷｬｲ')
      call t.add_map('kgh', 'ｷｭｳ')
      call t.add_map('kgw', 'ｷｪｲ')
      call t.add_map('kgp', 'ｷｮｳ')
      call t.add_map('syq', 'ｼｬｲ')
      call t.add_map('syh', 'ｼｭｳ')
      call t.add_map('syw', 'ｼｪｲ')
      call t.add_map('syp', 'ｼｮｳ')
      call t.add_map('xq', 'ｼｬｲ')
      call t.add_map('xh', 'ｼｭｳ')
      call t.add_map('xw', 'ｼｪｲ')
      call t.add_map('xp', 'ｼｮｳ')
      call t.add_map('tyq', 'ﾁｬｲ')
      call t.add_map('tyh', 'ﾁｭｳ')
      call t.add_map('tyw', 'ﾁｪｲ')
      call t.add_map('typ', 'ﾁｮｳ')
      call t.add_map('cq', 'ﾁｬｲ')
      call t.add_map('ch', 'ﾁｭｳ')
      call t.add_map('cw', 'ﾁｪｲ')
      call t.add_map('cp', 'ﾁｮｳ')
      call t.add_map('nyq', 'ﾆｬｲ')
      call t.add_map('nyh', 'ﾆｭｳ')
      call t.add_map('nyw', 'ﾆｪｲ')
      call t.add_map('nyp', 'ﾆｮｳ')
      call t.add_map('ngq', 'ﾆｬｲ')
      call t.add_map('ngh', 'ﾆｭｳ')
      call t.add_map('ngw', 'ﾆｪｲ')
      call t.add_map('ngp', 'ﾆｮｳ')
      call t.add_map('hyq', 'ﾋｬｲ')
      call t.add_map('hyh', 'ﾋｭｳ')
      call t.add_map('hyw', 'ﾋｪｲ')
      call t.add_map('hyp', 'ﾋｮｳ')
      call t.add_map('hgq', 'ﾋｬｲ')
      call t.add_map('hgh', 'ﾋｭｳ')
      call t.add_map('hgw', 'ﾋｪｲ')
      call t.add_map('hgp', 'ﾋｮｳ')
      call t.add_map('myq', 'ﾐｬｲ')
      call t.add_map('myh', 'ﾐｭｳ')
      call t.add_map('myw', 'ﾐｪｲ')
      call t.add_map('myp', 'ﾐｮｳ')
      call t.add_map('mgq', 'ﾐｬｲ')
      call t.add_map('mgh', 'ﾐｭｳ')
      call t.add_map('mgw', 'ﾐｪｲ')
      call t.add_map('mgp', 'ﾐｮｳ')
      call t.add_map('ryq', 'ﾘｬｲ')
      call t.add_map('ryh', 'ﾘｭｳ')
      call t.add_map('ryw', 'ﾘｪｲ')
      call t.add_map('ryp', 'ﾘｮｳ')
      call t.add_map('gya', 'ｷﾞｬ')
      call t.add_map('gyu', 'ｷﾞｭ')
      call t.add_map('gye', 'ｷﾞｪ')
      call t.add_map('gyo', 'ｷﾞｮ')
      call t.add_map('zya', 'ｼﾞｬ')
      call t.add_map('zyu', 'ｼﾞｭ')
      call t.add_map('zye', 'ｼﾞｪ')
      call t.add_map('zyo', 'ｼﾞｮ')
      call t.add_map('jya', 'ｼﾞｬ')
      call t.add_map('jyu', 'ｼﾞｭ')
      call t.add_map('jye', 'ｼﾞｪ')
      call t.add_map('jyo', 'ｼﾞｮ')
      call t.add_map('ja', 'ｼﾞｬ')
      call t.add_map('ji', 'ｼﾞ')
      call t.add_map('ju', 'ｼﾞｭ')
      call t.add_map('je', 'ｼﾞｪ')
      call t.add_map('jo', 'ｼﾞｮ')
      call t.add_map('bya', 'ﾋﾞｬ')
      call t.add_map('byu', 'ﾋﾞｭ')
      call t.add_map('bye', 'ﾋﾞｪ')
      call t.add_map('byo', 'ﾋﾞｮ')
      call t.add_map('pya', 'ﾋﾟｬ')
      call t.add_map('pyu', 'ﾋﾟｭ')
      call t.add_map('pye', 'ﾋﾟｪ')
      call t.add_map('pyo', 'ﾋﾟｮ')
      call t.add_map('pga', 'ﾋﾟｬ')
      call t.add_map('pgi', 'ｲ')
      call t.add_map('pgu', 'ﾋﾟｭ')
      call t.add_map('pge', 'ﾋﾟｪ')
      call t.add_map('pgo', 'ﾋﾟｮ')
      call t.add_map('gyz', 'ｷﾞｬﾝ')
      call t.add_map('gyn', 'ｷﾞｬﾝ')
      call t.add_map('gyj', 'ｷﾞｭﾝ')
      call t.add_map('gyd', 'ｷﾞｪﾝ')
      call t.add_map('gyl', 'ｷﾞｮﾝ')
      call t.add_map('zyz', 'ｼﾞｬﾝ')
      call t.add_map('zyn', 'ｼﾞｬﾝ')
      call t.add_map('zyj', 'ｼﾞｭﾝ')
      call t.add_map('zyd', 'ｼﾞｪﾝ')
      call t.add_map('zyl', 'ｼﾞｮﾝ')
      call t.add_map('jz', 'ｼﾞｬﾝ')
      call t.add_map('jn', 'ｼﾞｬﾝ')
      call t.add_map('jk', 'ｼﾞﾝ')
      call t.add_map('jj', 'ｼﾞｭﾝ')
      call t.add_map('jd', 'ｼﾞｪﾝ')
      call t.add_map('jl', 'ｼﾞｮﾝ')
      call t.add_map('byz', 'ﾋﾞｬﾝ')
      call t.add_map('byn', 'ﾋﾞｬﾝ')
      call t.add_map('byj', 'ﾋﾞｭﾝ')
      call t.add_map('byd', 'ﾋﾞｪﾝ')
      call t.add_map('byl', 'ﾋﾞｮﾝ')
      call t.add_map('pyz', 'ﾋﾟｬﾝ')
      call t.add_map('pyn', 'ﾋﾟｬﾝ')
      call t.add_map('pyj', 'ﾋﾟｭﾝ')
      call t.add_map('pyd', 'ﾋﾟｪﾝ')
      call t.add_map('pyl', 'ﾋﾟｮﾝ')
      call t.add_map('pgz', 'ﾋﾟｬﾝ')
      call t.add_map('pgn', 'ﾋﾟｬﾝ')
      call t.add_map('pgj', 'ﾋﾟｭﾝ')
      call t.add_map('pgd', 'ﾋﾟｪﾝ')
      call t.add_map('pgl', 'ﾋﾟｮﾝ')
      call t.add_map('gyq', 'ｷﾞｬｲ')
      call t.add_map('gyh', 'ｷﾞｭｳ')
      call t.add_map('gyw', 'ｷﾞｪｲ')
      call t.add_map('gyp', 'ｷﾞｮｳ')
      call t.add_map('zyq', 'ｼﾞｬｲ')
      call t.add_map('zyh', 'ｼﾞｭｳ')
      call t.add_map('zyw', 'ｼﾞｪｲ')
      call t.add_map('zyp', 'ｼﾞｮｳ')
      call t.add_map('jq', 'ｼﾞｬｲ')
      call t.add_map('jh', 'ｼﾞｭｳ')
      call t.add_map('jw', 'ｼﾞｪｲ')
      call t.add_map('jp', 'ｼﾞｮｳ')
      call t.add_map('byq', 'ﾋﾞｬｲ')
      call t.add_map('byh', 'ﾋﾞｭｳ')
      call t.add_map('byw', 'ﾋﾞｪｲ')
      call t.add_map('byp', 'ﾋﾞｮｳ')
      call t.add_map('pyq', 'ﾋﾟｬｲ')
      call t.add_map('pyh', 'ﾋﾟｭｳ')
      call t.add_map('pyw', 'ﾋﾟｪｲ')
      call t.add_map('pyp', 'ﾋﾟｮｳ')
      call t.add_map('pgq', 'ﾋﾟｬｲ')
      call t.add_map('pgh', 'ﾋﾟｭｳ')
      call t.add_map('pgw', 'ﾋﾟｪｲ')
      call t.add_map('pgp', 'ﾋﾟｮｳ')
      call t.add_map('va', 'ｳﾞｧ')
      call t.add_map('vi', 'ｳﾞｨ')
      call t.add_map('vu', 'ｳﾞ')
      call t.add_map('ve', 'ｳﾞｪ')
      call t.add_map('vo', 'ｳﾞｫ')
      call t.add_map('tgi', 'ﾃｨ')
      call t.add_map('tgu', 'ﾄｩ')
      call t.add_map('dci', 'ﾃﾞｨ')
      call t.add_map('dcu', 'ﾄﾞｩ')
      call t.add_map('xxa', 'ｧ')
      call t.add_map('xxi', 'ｨ')
      call t.add_map('xxu', 'ｩ')
      call t.add_map('xxe', 'ｪ')
      call t.add_map('xxo', 'ｫ')
      call t.add_map('xya', 'ｬ')
      call t.add_map('xyu', 'ｭ')
      call t.add_map('xyo', 'ｮ')
      call t.add_map('xwa', 'ヮ')
      call t.add_map('xtsu', 'ｯ')
      call t.add_map('xtu', 'ｯ')
      call t.add_map(';', 'ｯ')
      call t.add_map('t;', 'ｯ')
      call t.add_map('kt', 'ｺﾄ')
      call t.add_map('st', 'ｼﾀ')
      call t.add_map('tt', 'ﾀﾁ')
      call t.add_map('ht', 'ﾋﾄ')
      call t.add_map('wt', 'ﾜﾀ')
      call t.add_map('mn', 'ﾓﾉ')
      call t.add_map('ms', 'ﾏｽ')
      call t.add_map('ds', 'ﾃﾞｽ')
      call t.add_map('km', 'ｶﾓ')
      call t.add_map('tm', 'ﾀﾒ')
      call t.add_map('dm', 'ﾃﾞﾓ')
      call t.add_map('kr', 'ｶﾗ')
      call t.add_map('sr', 'ｽﾙ')
      call t.add_map('tr', 'ﾀﾗ')
      call t.add_map('nr', 'ﾅﾙ')
      call t.add_map('yr', 'ﾖﾙ')
      call t.add_map('rr', 'ﾗﾚ')
      call t.add_map('zr', 'ｻﾞﾙ')
      call t.add_map('mt', 'ﾏﾀ')
      call t.add_map('tb', 'ﾀﾋﾞ')
      call t.add_map('nb', 'ﾈﾊﾞ')
      call t.add_map('bt', 'ﾋﾞﾄ')
      call t.add_map('gr', 'ｶﾞﾗ')
      call t.add_map('gt', 'ｺﾞﾄ')
      call t.add_map('nt', 'ﾆﾁ')
      call t.add_map('dt', 'ﾀﾞﾁ')
      call t.add_map('wr', 'ﾜﾚ')
      call eskk#register_mode_table('hankata', t) "}}}
    endif "}}}
  endfunction "}}}
  function! s:eskk_initial_post() abort "{{{
    if g:eskk#use_azik
      EskkUnmap -type=mode:hira:toggle-kata q
      EskkUnmap -type=mode:hira:q-key q
      EskkUnmap -type=mode:hira:l-key l
      EskkUnmap -type=mode:kata:toggle-kata q
      EskkUnmap -type=mode:kata:q-key q
      EskkUnmap -type=mode:kata:l-key l
      EskkUnmap -type=mode:hankata:toggle-kata q
      EskkUnmap -type=mode:hankata:q-key q
      EskkUnmap -type=mode:hankata:l-key l
      EskkUnmap -type=sticky ;
      EskkUnmap -type=phase:henkan-select:delete-from-dict X
      EskkMap -type=phase:henkan-select:delete-from-dict <M-x>
      if g:eskk#azik_keyboard_type=="jp106"
        EskkMap -type=mode:hira:toggle-kata @
        EskkMap -type=mode:hira:q-key @
        EskkMap -type=mode:kata:toggle-kata @
        EskkMap -type=mode:kata:q-key @
        EskkMap -type=mode:hankata:toggle-kata @
        EskkMap -type=mode:hankata:q-key @
      elseif g:eskk#azik_keyboard_type=="us101"
        EskkMap -type=mode:hira:toggle-kata [
        EskkMap -type=mode:hira:q-key [
        EskkMap -type=mode:kata:toggle-kata [
        EskkMap -type=mode:kata:q-key [
        EskkMap -type=mode:hankata:toggle-kata [
        EskkMap -type=mode:hankata:q-key [
      endif
    endif
  endfunction "}}}
endif "}}}
"   map {{{
noremap Y y$
noremap ; :
noremap : ;
noremap <F3> n
if exists('*strftime')
  inoremap <expr> <F5> strftime(g:changelog_dateformat)
endif
if has('keymap') "{{{
  function! g:ToggleJcuken()
    if &keymap!="russian-jcukenwin"
      set keymap=russian-jcukenwin
    else
      set keymap&
    endif
  endfunction
  inoremap <C-r> <Esc>:call ToggleJcuken()<CR>a
endif "}}}
inoremap ( ()<LEFT>
inoremap [ []<LEFT>
inoremap { {}<LEFT>
inoremap <Up> <C-o>gk
inoremap <Down> <C-o>gj
nnoremap <Up> gk
nnoremap <Down> gj
vnoremap <C-a> <C-a>gv
vnoremap <C-x> <C-x>gv
vnoremap < <gv
vnoremap > >gv
" }}}
" options {{{
silent! while 0
  set nocompatible
silent! endwhile
set ambiwidth=double
if has('autochdir')
  set autochdir
endif
set autoread
set backspace=indent,eol,start
set nobackup
if has('patch-7.4.793')
  set belloff=all
endif
set breakindent
set breakindentopt=min:20,shift:-2,sbr
if has('unnamedplus')
  set clipboard=unnamedplus
else
  set clipboard=unnamed
endif
set concealcursor=
set conceallevel=2
set cpoptions+=n
if has('cryptv')
  if has('patch-7.4.399')
    set cryptmethod=blowfish2
  elseif v:version >= 703
    set cryptmethod=blowfish
  endif
endif
if has('syntax')
  set cursorline
  set cursorlineopt=number
endif
set errorbells
set expandtab
set fileencodings=ucs-bom,utf-8,default,iso-2022-jp,euc-jp,sjis,cp932,latin1
if has('folding')
  set foldmethod=syntax
endif
set helpheight=50
set hidden
set incsearch
set keywordprg=:help
set laststatus=1
set linebreak
set listchars=tab:>-,trail:_
set matchtime=1
if has('mouse')
  if executable('toolbox')
    set mouse=a
  else
    set mouse=ch
  endif
endif
set regexpengine=1
set shiftround
set shortmess+=A
set shortmess-=S
set shortmess-=s
if has('linebreak')
  set showbreak=>\ 
endif
set showcmd
set smartcase
set smarttab
set softtabstop=-1
set spelllang=en,cjk
set nostartofline
set noswapfile
set title
set timeout
set timeoutlen=400                      " $VIMRUNTIME/keymap/korean.vim
set ttimeout
set ttimeoutlen=100
if has('persistent_undo')
  set undodir=~/tmp,~/
  set noundofile
endif
set virtualedit=block
set visualbell
set whichwrap=b,s,~
set wildmenu
set writebackup
" }}}
" vim: foldmethod=marker commentstring="%s nospell
