colorscheme industry
filetype plugin indent on
let loaded_matchparen=1
set autochdir
set backspace=indent,eol,start
set bg=dark
set bo=all
set clipboard=unnamed
set nocp
set et
set is
set lcs=tab:>-,trail:_
set showcmd
set sta
set sts=-1
set noswapfile
set title
set ttimeoutlen=0
set t_Co=256
set ww=b,s,~
set wildmenu
source ~/.exrc
syntax enable
